### ISSUE TITLE
The docs and examples don't say where to put test files.

### ISSUE THREAD

**Issue by rafalkrupinski** [metachris/typescript-boilerplate#14]
## Expected Behavior

I was expecting to learn where to put my test files.

## Actual Behavior

The docs and examples don't say where to put test files.

## Steps to Reproduce the Problem

1. Read the documentation

**Comment by metachris** [comment]
You can put them anywhere, like into `src/`. Example: https://github.com/metachris/typescript-boilerplate/blob/master/src/main.test.ts

**Comment by rafalkrupinski** [comment]
I tried putting it in tests or ```__tests__```, but it doesn't work :/

**Comment by metachris** [comment]
I see. How about putting it into `src/`? Like this example: https://github.com/metachris/typescript-boilerplate/blob/master/src/main.test.ts

**Comment by rafalkrupinski** [comment]
Yeah, that works.

It's not obvious for someone with a background in other languages like Java, where you typically keep your tests in a directory separate from src. It's not mentioned anywhere and I've missed the test file in the boilerplate repo.

Cheers

edit:
oh, and the regex in jest config specifically mentions tests and ```__tests__```, so that's extra confusing

**Comment by metachris** [comment]
Yeah I understand! I think that pattern means to use `__tests__` but only if inside another directory 🤔 
You could update the pattern to include any root test directory you want to use: https://github.com/metachris/typescript-boilerplate/blob/master/jest.config.js

Thanks for the issue :)
