### ISSUE TITLE
Make it configurable with charmix

### ISSUE THREAD

**Issue by vitonsky** [metachris/typescript-boilerplate#19]
Hi. Could you add archetype manifest for [charmix](https://github.com/vitonsky/charmix)?

You may make a static archetype just by add one json file or you make it configurable if will implement hook for archetype.
Read more about: https://github.com/vitonsky/charmix/blob/master/docs/CreateArchetype.md

**Comment by metachris** [comment]
If you create a PR I'd consider it. Until then I'm closing the issue
