### ISSUE TITLE
Lint and test passing for wrong project

### ISSUE THREAD

**Issue by adrian-burlacu-software** [metachris/typescript-boilerplate#6]
## Expected Behavior
Just tried using this template for my TS project and when I click the Lint&test passing button, it should refer to my project.

## Actual Behavior
The button points to: https://github.com/metachris/micropython-ctl/actions?query=workflow%3A%22Build+and+test%22

## Steps to Reproduce the Problem

1. Create new Github project with this template.
2. Press button on github.

## Specifications

- Version: 0.4.2
- Platform: Github

**Comment by metachris** [comment]
Thanks for the report! You can fix this by changing the url in your readme.

Will fix it in this too tonight

**Comment by metachris** [comment]
Fixed in https://github.com/metachris/typescript-boilerplate/commit/d5daaf73a6b8ad44d0da3bc7915c3ecf4eb9138b
